### ISSUE TITLE
Kernel support for ovpn-dco missing, disabling data channel offload.

### ISSUE THREAD

**Issue by Comandante1977** [purum-pum-pum/openvpn-DCO-conf#1]
Все сделал почти по написанному.
Скачал исходники модуля. Скомпилировал. Вручную запустил modprobe ovpn-dco-v2
Получилось так (lsmod):
ovpn_dco_v2            77824  0
ip6_udp_tunnel         16384  1 ovpn_dco_v2
udp_tunnel             20480  1 ovpn_dco_v2

Установил Openvpn из дебиановского репозитория. Скомпилирован с enable_dco=yes

В логе все равно:
Note: Kernel support for ovpn-dco missing, disabling data channel offload.

Вопрос что не так....

**Comment by purum-pum-pum** [comment]
Здравствуйте.
1) нет необходимости загружать вручную модуль ядра. Клиент openvpn сам это сделает когда запустите.
2) внесены изменения как я знаю, и модуль ядра нужно запускать строго с последними версиями клиента openvpn с гитхаба

Также хочу заметить что я не уделял времени вопросу сборки модуля с dkms. Это значит что по по инструкции модуль ядра может собраться без поддержки dkms, и при обновлении ядра_(apt dist-upgrade если про debian подобные дистрибутивы говорим)_ у вас слетит модуль, его придется устанавливать снова

**Comment by purum-pum-pum** [comment]
> Все сделал почти по написанному. Скачал исходники модуля. Скомпилировал. Вручную запустил modprobe ovpn-dco-v2 Получилось так (lsmod): ovpn_dco_v2 77824 0 ip6_udp_tunnel 16384 1 ovpn_dco_v2 udp_tunnel 20480 1 ovpn_dco_v2
> 
> Установил Openvpn из дебиановского репозитория. Скомпилирован с enable_dco=yes
> 
> В логе все равно: Note: Kernel support for ovpn-dco missing, disabling data channel offload.
> 
> Вопрос что не так....

Здравствуйте.
1) нет необходимости загружать вручную модуль ядра. Клиент openvpn сам это сделает когда запустите.
2) внесены изменения как я знаю, и модуль ядра нужно запускать строго с последними версиями клиента openvpn с гитхаба

Также хочу заметить что я не уделял времени вопросу сборки модуля с dkms. Это значит что по по инструкции модуль ядра может собраться без поддержки dkms, и при обновлении ядра _(apt dist-upgrade если про debian подобные дистрибутивы говорим)_  у вас слетит модуль, его придется устанавливать снова

**Comment by Comandante1977** [comment]
День добрый!

Спасибо за ответ! В ветке dco уже подсказали, что модуль ovpn-dco-v2 работает только с версией openvpn 2.6.2.
А я ставил 2.6.1
Как раз сегодня она (2.6.2) в репах появилась (лень было самому собирать ))) 

Вроде все работает. Теперь разбираюсь с новшествами-глюками ))) Как обычно.
Например explicit-exit-notify перестал работать. (((
